export const CS_MAPS_CONFIG = [
    {
        id: 'cs_miyagi',
        name: '微地形図（宮城県）',
        bounds: [[37.45, 140.07], [39.01, 141.46]],
        url: 'https://forestgeo.info/opendata/4_miyagi/topography_2023/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 23,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-miyagi-maptiles">宮城県・微地形表現図マップタイル（林野庁加工）</a>',
    },
    {   
        id: 'cs_tochigi',
        name: '微地形図（栃木県）',
        bounds: [[36.19, 139.32], [37.15, 140.30]],
        url: 'https://rinya-tochigi.geospatial.jp/2023/rinya/tile/csmap/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset?organization=tochigipref-shinrin-seibi">栃木県「微地形図（CS立体図）」</a>',
    },
    {
        id: 'cs_saitama',
        name: '微地形図（埼玉県）',
        bounds: [[35.75, 138.71], [36.29, 139.90]],
        url: 'https://forestgeo.info/opendata/11_saitama/csmap/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 23,
        tms: false,
        attribution: '埼玉県・微地形表現図・林野庁加工</a>',
    },
    {
        id: 'cs_tokyo',
        name: '微地形図（東京都（多摩地域））',
        bounds: [[35.52, 138.91], [35.90, 139.97]],
        url: 'https://forestgeo.info/opendata/13_tokyo/inyouzu_2022/{z}/{x}/{y}.webp',
        minZoom: 14,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-tokyo-maptiles">東京都・陰陽図（多摩地域2022）林野庁加工</a>',
    },
    {
        id: 'cs_kanagawa',
        name: '微地形図（神奈川県）',
        bounds: [[35.12, 138.91], [35.68, 139.84]],
        url: 'https://forestgeo.info/opendata/14_kanagawa/rrim_2022/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-kanagawa-maptiles">神奈川県・微地形表現図（2019-2022）林野庁加工</a>',
    },
    {
        id: 'cs_toyama',
        name: '微地形図（富山県）',
        bounds: [[36.27, 136.76], [36.98, 137.77]],
        url:  'https://rinya-toyama.geospatial.jp/tile/rinya/2024/rrimap/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rrimap">富山県森林資源データ</a>',
    },      
    {
        id: 'cs_yamanashi',
        name: '微地形図（山梨県）',
        bounds: [[35.16, 138.18], [35.98, 139.14]],
        url:'https://forestgeo.info/opendata/19_yamanashi/inyouzu_2024/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-yamanashi-maptiles">山梨県・微地形表現図（陰陽図）マップタイル（林野庁加工）</a>',
    },
    {
        id: 'cs_nagano',
        name: 'CS立体図（長野県）',
        bounds: [[35.19, 137.32], [37.15, 138.74]],
        url: 'https://tile.geospatial.jp/CS/VER2/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/nagano-csmap">CS立体図 Ver.2 （１ｍ）タイル配信</a>',
    },
    {
        id: 'cs_aichi',
        name: '微地形図（愛知県）',
        url: 'https://salmonzebra2.sakura.ne.jp/webmap/toyota_web_map_20231030/cs_toyota/{z}/{x}/{y}.jpg',
        bounds: [[34.57, 136.67], [35.43, 137.84]], 
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 23,
        attribution: '愛知県平成30年度航空レーザ測量データを改変'
    },
    {
        id: 'cs_gifu',
        name: '微地形図（岐阜県）',
        url: 'https://forestgeo.info/opendata/21_gifu/csmap_2023/{z}/{x}/{y}.webp',
        bounds: [[35.13, 136.27], [36.47, 137.65]], 
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-gifu-maptiles">岐阜県森林研究所・CS立体図（2023/林野庁加工）</a>',
    },  
    {
        id: 'cs_shizuoka',
        name: 'CS立体図（静岡県）',
        url: 'https://forestgeo.info/opendata/22_shizuoka/csmap_2023/{z}/{x}/{y}.webp',
        bounds: [[34.57, 137.47], [35.65, 139.18]],
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-shizuoka-maptiles">静岡県・微地形表現図マップタイル（林野庁加工）</a>',
    },
    {
        id: 'cs_shiga',
        name: '微地形図（滋賀県）',
        bounds: [[34.79, 135.76], [35.71, 136.46]],
        url:  'https://forestgeo.info/opendata/25_shiga/csmap_2023/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 23,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-shiga-maptiles">滋賀県・微地形表現図（CS立体図/2023）林野庁加工</a>',
    },
    {     
        id: 'cs_kyoto',
        name: '微地形図（京都府）',
        bounds: [[34.70, 134.85], [35.78, 136.06]],
        url:'https://rinya-kyoto.geospatial.jp/tile/rinya/2024/rrim_KyotoPref/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rrimap_kyotopref">：京都府オープンデータ</a>',
    },
    {
        id: 'cs_osaka',
        name: '微地形図（大阪府）',
        bounds: [[34.27, 135.09], [35.06, 135.75]],
        url:  'https://forestgeo.info/opendata/27_osaka/csmap_2020/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-osaka-maptiles">大阪府・CS立体図（2019-2020）林野庁加工</a>',
    },
    {
        id: 'cs_hyogo',
        name: '微地形図（兵庫県）',
        bounds: [[34.15, 134.25], [35.68, 135.47]],
        url: 'https://rinya-hyogo.geospatial.jp/2023/rinya/tile/csmap/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution:  '<a href="https://www.geospatial.jp/ckan/dataset?organization=hyogopref/">兵庫県50㎝メッシュCS立体図（xyzタイル）、兵庫県</a>',
    }, 
    {
        id: 'cs_okayama',
        name: '微地形図（岡山県）',
        bounds: [[34.29, 133.26], [35.36, 134.42]],
        url:'https://forestgeo.info/opendata/33_okayama/csmap_2024/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 23,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-okayama-maptiles">岡山県・微地形表現図マップタイル（林野庁加工）</a>',
    },
    {
        id: 'cs_ehime',
        name: '微地形図（愛媛県）',
        bounds: [[32.88, 132.01], [34.30, 133.70]],
        url:'https://rinya-ehime.geospatial.jp/tile/rinya/2024/csmap_Ehime/{z}/{x}/{-y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/csmap_ehime">愛媛県森林資源データ</a>',
    },
    {
        id: 'cs_kochi',
        name: '微地形図（高知県）',
        bounds: [[32.70, 132.47], [33.89, 134.32]],
        url:'https://rinya-kochi.geospatial.jp/2023/rinya/tile/csmap/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset?organization=kochipref-mori">高知県「微地形図（CS立体図）</a>',
    },
    {
        id: 'cs_nagasaki',
        name: '微地形図（長崎県）',
        bounds: [[31.98, 128.10], [34.73, 130.40]],
        url: 'https://forestgeo.info/opendata/42_nagasaki/rrim_2022/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-nagasaki-maptiles/resource/cb8a872b-30a4-4281-9394-f9a934593889">長崎県・微地形表現図（赤色立体地図/地形起伏図2022）林野庁加工</a>',
    },
];

export const FOREST_TYPE_MAPS_CONFIG = [
    {   
        id: 'ft_tochigi',
        name: '林相識別図（栃木県）',
        bounds: [[36.19, 139.32], [37.15, 140.30]],
        url: 'https://rinya-tochigi.geospatial.jp/2023/rinya/tile/ls_standtype/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset?organization=tochigipref-shinrin-seibi">栃木県「レーザ林相図」</a>',
    },
    {
        id: 'ft_kanagawa',
        name: '林相識別図（神奈川県）',
        bounds: [[35.12, 138.91], [35.68, 139.84]],
        url: 'https://forestgeo.info/opendata/14_kanagawa/ls_standtype_2020/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-kanagawa-maptiles">神奈川県・林相識別図（2019-2022）林野庁加工</a>',
    },
        {
        id: 'ft_toyama',
        name: '林相識別図（富山県）',
        bounds: [[36.39, 136.35], [37.09, 137.46]],
        url:  'https://forestgeo.info/opendata/16_toyama/ls_standtype_2021/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rrimap">富山県森林資源データ</a>',
    },
        {
        id: 'ft_shiga',
        name: '林相識別図（滋賀県）',
        bounds: [[34.79, 135.76], [35.71, 136.46]],
        url:  'https://forestgeo.info/opendata/25_shiga/ls_standtype_2023/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 23,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rinya-shiga-maptiles">滋賀県・林相識別図（2023）林野庁加工</a>',
    },
    {     
        id: 'ft_kyoto',
        name: '林相識別図（京都府）',
        bounds: [[34.70, 134.85], [35.78, 136.06]],
        url:'https://rinya-kyoto.geospatial.jp/tile/rinya/2024/rrim_KyotoPref/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/rrimap_kyotopref">：京都府オープンデータ</a>',
    },
    {
        id: 'ft_hyogo',
        name: '林相識別図（兵庫県）',
        bounds: [[34.15, 134.25], [35.68, 135.47]],
        url: 'https://rinya-hyogo.geospatial.jp/2023/rinya/tile/ls_standtype/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution:  '<a href="https://www.geospatial.jp/ckan/dataset?organization=hyogopref/">兵庫県「レーザ林相図」、兵庫県</a>',
    },
    {
        id: 'ft_ehime',
        name: '林相識別図（愛媛県）',
        bounds: [[32.88, 132.01], [34.30, 133.70]],
        url:'https://rinya-ehime.geospatial.jp/tile/rinya/2024/ls_standtype_Ehime/{z}/{x}/{-y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset/ls_standtype_ehime">愛媛県森林資源データ</a>',
    },
    {
        id: 'ft_kochi',
        name: '林相識別図（高知県）',
        bounds: [[32.70, 132.47], [33.89, 134.32]],
        url:'https://rinya-kochi.geospatial.jp/2023/rinya/tile/ls_standtype/{z}/{x}/{y}.png',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://www.geospatial.jp/ckan/dataset?organization=kochipref-mori">高知県「レーザ林相図」</a>',
    },
    {
        id: 'ft_nagasaki',
        name: '林相識別図（長崎県）',
        bounds: [[31.98, 128.10], [34.73, 130.40]],
        url: 'https://forestgeo.info/opendata/42_nagasaki/ls_standtype_2022/{z}/{x}/{y}.webp',
        minZoom: 13,
        maxNativeZoom: 18,
        maxZoom: 20,
        tms: false,
        attribution: '<a href="https://forestgeo.info/opendata/42_nagasaki/ls_standtype_2022/{z}/{x}/{y}.webp">長崎県・林相識別図（2022）林野庁加工</a>',
    },
];